
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Notifications` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Notifications
 * 
 */
export type NotificationsModel = runtime.Types.Result.DefaultSelection<Prisma.$NotificationsPayload>

export type AggregateNotifications = {
  _count: NotificationsCountAggregateOutputType | null
  _min: NotificationsMinAggregateOutputType | null
  _max: NotificationsMaxAggregateOutputType | null
}

export type NotificationsMinAggregateOutputType = {
  id: string | null
  body: string | null
  createdAt: Date | null
  userId: string | null
}

export type NotificationsMaxAggregateOutputType = {
  id: string | null
  body: string | null
  createdAt: Date | null
  userId: string | null
}

export type NotificationsCountAggregateOutputType = {
  id: number
  body: number
  createdAt: number
  userId: number
  _all: number
}


export type NotificationsMinAggregateInputType = {
  id?: true
  body?: true
  createdAt?: true
  userId?: true
}

export type NotificationsMaxAggregateInputType = {
  id?: true
  body?: true
  createdAt?: true
  userId?: true
}

export type NotificationsCountAggregateInputType = {
  id?: true
  body?: true
  createdAt?: true
  userId?: true
  _all?: true
}

export type NotificationsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Notifications to aggregate.
   */
  where?: Prisma.NotificationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notifications to fetch.
   */
  orderBy?: Prisma.NotificationsOrderByWithRelationInput | Prisma.NotificationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NotificationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Notifications
  **/
  _count?: true | NotificationsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NotificationsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NotificationsMaxAggregateInputType
}

export type GetNotificationsAggregateType<T extends NotificationsAggregateArgs> = {
      [P in keyof T & keyof AggregateNotifications]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNotifications[P]>
    : Prisma.GetScalarType<T[P], AggregateNotifications[P]>
}




export type NotificationsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NotificationsWhereInput
  orderBy?: Prisma.NotificationsOrderByWithAggregationInput | Prisma.NotificationsOrderByWithAggregationInput[]
  by: Prisma.NotificationsScalarFieldEnum[] | Prisma.NotificationsScalarFieldEnum
  having?: Prisma.NotificationsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NotificationsCountAggregateInputType | true
  _min?: NotificationsMinAggregateInputType
  _max?: NotificationsMaxAggregateInputType
}

export type NotificationsGroupByOutputType = {
  id: string
  body: string | null
  createdAt: Date
  userId: string
  _count: NotificationsCountAggregateOutputType | null
  _min: NotificationsMinAggregateOutputType | null
  _max: NotificationsMaxAggregateOutputType | null
}

type GetNotificationsGroupByPayload<T extends NotificationsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NotificationsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NotificationsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NotificationsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NotificationsGroupByOutputType[P]>
      }
    >
  >



export type NotificationsWhereInput = {
  AND?: Prisma.NotificationsWhereInput | Prisma.NotificationsWhereInput[]
  OR?: Prisma.NotificationsWhereInput[]
  NOT?: Prisma.NotificationsWhereInput | Prisma.NotificationsWhereInput[]
  id?: Prisma.StringFilter<"Notifications"> | string
  body?: Prisma.StringNullableFilter<"Notifications"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Notifications"> | Date | string
  userId?: Prisma.StringFilter<"Notifications"> | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type NotificationsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type NotificationsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.NotificationsWhereInput | Prisma.NotificationsWhereInput[]
  OR?: Prisma.NotificationsWhereInput[]
  NOT?: Prisma.NotificationsWhereInput | Prisma.NotificationsWhereInput[]
  body?: Prisma.StringNullableFilter<"Notifications"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Notifications"> | Date | string
  userId?: Prisma.StringFilter<"Notifications"> | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type NotificationsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.NotificationsCountOrderByAggregateInput
  _max?: Prisma.NotificationsMaxOrderByAggregateInput
  _min?: Prisma.NotificationsMinOrderByAggregateInput
}

export type NotificationsScalarWhereWithAggregatesInput = {
  AND?: Prisma.NotificationsScalarWhereWithAggregatesInput | Prisma.NotificationsScalarWhereWithAggregatesInput[]
  OR?: Prisma.NotificationsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NotificationsScalarWhereWithAggregatesInput | Prisma.NotificationsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Notifications"> | string
  body?: Prisma.StringNullableWithAggregatesFilter<"Notifications"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Notifications"> | Date | string
  userId?: Prisma.StringWithAggregatesFilter<"Notifications"> | string
}

export type NotificationsCreateInput = {
  id?: string
  body?: string | null
  createdAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutNotificationsInput
}

export type NotificationsUncheckedCreateInput = {
  id?: string
  body?: string | null
  createdAt?: Date | string
  userId: string
}

export type NotificationsUpdateInput = {
  body?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutNotificationsNestedInput
}

export type NotificationsUncheckedUpdateInput = {
  body?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NotificationsCreateManyInput = {
  id?: string
  body?: string | null
  createdAt?: Date | string
  userId: string
}

export type NotificationsUpdateManyMutationInput = {
  body?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotificationsUncheckedUpdateManyInput = {
  body?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NotificationsListRelationFilter = {
  every?: Prisma.NotificationsWhereInput
  some?: Prisma.NotificationsWhereInput
  none?: Prisma.NotificationsWhereInput
}

export type NotificationsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NotificationsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type NotificationsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type NotificationsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  body?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type NotificationsCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.NotificationsCreateWithoutUserInput, Prisma.NotificationsUncheckedCreateWithoutUserInput> | Prisma.NotificationsCreateWithoutUserInput[] | Prisma.NotificationsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.NotificationsCreateOrConnectWithoutUserInput | Prisma.NotificationsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.NotificationsCreateManyUserInputEnvelope
  connect?: Prisma.NotificationsWhereUniqueInput | Prisma.NotificationsWhereUniqueInput[]
}

export type NotificationsUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.NotificationsCreateWithoutUserInput, Prisma.NotificationsUncheckedCreateWithoutUserInput> | Prisma.NotificationsCreateWithoutUserInput[] | Prisma.NotificationsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.NotificationsCreateOrConnectWithoutUserInput | Prisma.NotificationsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.NotificationsCreateManyUserInputEnvelope
  connect?: Prisma.NotificationsWhereUniqueInput | Prisma.NotificationsWhereUniqueInput[]
}

export type NotificationsUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationsCreateWithoutUserInput, Prisma.NotificationsUncheckedCreateWithoutUserInput> | Prisma.NotificationsCreateWithoutUserInput[] | Prisma.NotificationsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.NotificationsCreateOrConnectWithoutUserInput | Prisma.NotificationsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.NotificationsUpsertWithWhereUniqueWithoutUserInput | Prisma.NotificationsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.NotificationsCreateManyUserInputEnvelope
  set?: Prisma.NotificationsWhereUniqueInput | Prisma.NotificationsWhereUniqueInput[]
  disconnect?: Prisma.NotificationsWhereUniqueInput | Prisma.NotificationsWhereUniqueInput[]
  delete?: Prisma.NotificationsWhereUniqueInput | Prisma.NotificationsWhereUniqueInput[]
  connect?: Prisma.NotificationsWhereUniqueInput | Prisma.NotificationsWhereUniqueInput[]
  update?: Prisma.NotificationsUpdateWithWhereUniqueWithoutUserInput | Prisma.NotificationsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.NotificationsUpdateManyWithWhereWithoutUserInput | Prisma.NotificationsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.NotificationsScalarWhereInput | Prisma.NotificationsScalarWhereInput[]
}

export type NotificationsUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.NotificationsCreateWithoutUserInput, Prisma.NotificationsUncheckedCreateWithoutUserInput> | Prisma.NotificationsCreateWithoutUserInput[] | Prisma.NotificationsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.NotificationsCreateOrConnectWithoutUserInput | Prisma.NotificationsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.NotificationsUpsertWithWhereUniqueWithoutUserInput | Prisma.NotificationsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.NotificationsCreateManyUserInputEnvelope
  set?: Prisma.NotificationsWhereUniqueInput | Prisma.NotificationsWhereUniqueInput[]
  disconnect?: Prisma.NotificationsWhereUniqueInput | Prisma.NotificationsWhereUniqueInput[]
  delete?: Prisma.NotificationsWhereUniqueInput | Prisma.NotificationsWhereUniqueInput[]
  connect?: Prisma.NotificationsWhereUniqueInput | Prisma.NotificationsWhereUniqueInput[]
  update?: Prisma.NotificationsUpdateWithWhereUniqueWithoutUserInput | Prisma.NotificationsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.NotificationsUpdateManyWithWhereWithoutUserInput | Prisma.NotificationsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.NotificationsScalarWhereInput | Prisma.NotificationsScalarWhereInput[]
}

export type NotificationsCreateWithoutUserInput = {
  id?: string
  body?: string | null
  createdAt?: Date | string
}

export type NotificationsUncheckedCreateWithoutUserInput = {
  id?: string
  body?: string | null
  createdAt?: Date | string
}

export type NotificationsCreateOrConnectWithoutUserInput = {
  where: Prisma.NotificationsWhereUniqueInput
  create: Prisma.XOR<Prisma.NotificationsCreateWithoutUserInput, Prisma.NotificationsUncheckedCreateWithoutUserInput>
}

export type NotificationsCreateManyUserInputEnvelope = {
  data: Prisma.NotificationsCreateManyUserInput | Prisma.NotificationsCreateManyUserInput[]
}

export type NotificationsUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.NotificationsWhereUniqueInput
  update: Prisma.XOR<Prisma.NotificationsUpdateWithoutUserInput, Prisma.NotificationsUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.NotificationsCreateWithoutUserInput, Prisma.NotificationsUncheckedCreateWithoutUserInput>
}

export type NotificationsUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.NotificationsWhereUniqueInput
  data: Prisma.XOR<Prisma.NotificationsUpdateWithoutUserInput, Prisma.NotificationsUncheckedUpdateWithoutUserInput>
}

export type NotificationsUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.NotificationsScalarWhereInput
  data: Prisma.XOR<Prisma.NotificationsUpdateManyMutationInput, Prisma.NotificationsUncheckedUpdateManyWithoutUserInput>
}

export type NotificationsScalarWhereInput = {
  AND?: Prisma.NotificationsScalarWhereInput | Prisma.NotificationsScalarWhereInput[]
  OR?: Prisma.NotificationsScalarWhereInput[]
  NOT?: Prisma.NotificationsScalarWhereInput | Prisma.NotificationsScalarWhereInput[]
  id?: Prisma.StringFilter<"Notifications"> | string
  body?: Prisma.StringNullableFilter<"Notifications"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Notifications"> | Date | string
  userId?: Prisma.StringFilter<"Notifications"> | string
}

export type NotificationsCreateManyUserInput = {
  id?: string
  body?: string | null
  createdAt?: Date | string
}

export type NotificationsUpdateWithoutUserInput = {
  body?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotificationsUncheckedUpdateWithoutUserInput = {
  body?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotificationsUncheckedUpdateManyWithoutUserInput = {
  body?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type NotificationsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  body?: boolean
  createdAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.Notifications$userArgs<ExtArgs>
}, ExtArgs["result"]["notifications"]>



export type NotificationsSelectScalar = {
  id?: boolean
  body?: boolean
  createdAt?: boolean
  userId?: boolean
}

export type NotificationsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "body" | "createdAt" | "userId", ExtArgs["result"]["notifications"]>
export type NotificationsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.Notifications$userArgs<ExtArgs>
}

export type $NotificationsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Notifications"
  objects: {
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    body: string | null
    createdAt: Date
    userId: string
  }, ExtArgs["result"]["notifications"]>
  composites: {}
}

export type NotificationsGetPayload<S extends boolean | null | undefined | NotificationsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NotificationsPayload, S>

export type NotificationsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NotificationsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NotificationsCountAggregateInputType | true
  }

export interface NotificationsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Notifications'], meta: { name: 'Notifications' } }
  /**
   * Find zero or one Notifications that matches the filter.
   * @param {NotificationsFindUniqueArgs} args - Arguments to find a Notifications
   * @example
   * // Get one Notifications
   * const notifications = await prisma.notifications.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NotificationsFindUniqueArgs>(args: Prisma.SelectSubset<T, NotificationsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NotificationsClient<runtime.Types.Result.GetResult<Prisma.$NotificationsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Notifications that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NotificationsFindUniqueOrThrowArgs} args - Arguments to find a Notifications
   * @example
   * // Get one Notifications
   * const notifications = await prisma.notifications.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NotificationsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NotificationsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotificationsClient<runtime.Types.Result.GetResult<Prisma.$NotificationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Notifications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationsFindFirstArgs} args - Arguments to find a Notifications
   * @example
   * // Get one Notifications
   * const notifications = await prisma.notifications.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NotificationsFindFirstArgs>(args?: Prisma.SelectSubset<T, NotificationsFindFirstArgs<ExtArgs>>): Prisma.Prisma__NotificationsClient<runtime.Types.Result.GetResult<Prisma.$NotificationsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Notifications that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationsFindFirstOrThrowArgs} args - Arguments to find a Notifications
   * @example
   * // Get one Notifications
   * const notifications = await prisma.notifications.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NotificationsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NotificationsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotificationsClient<runtime.Types.Result.GetResult<Prisma.$NotificationsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Notifications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Notifications
   * const notifications = await prisma.notifications.findMany()
   * 
   * // Get first 10 Notifications
   * const notifications = await prisma.notifications.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const notificationsWithIdOnly = await prisma.notifications.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NotificationsFindManyArgs>(args?: Prisma.SelectSubset<T, NotificationsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Notifications.
   * @param {NotificationsCreateArgs} args - Arguments to create a Notifications.
   * @example
   * // Create one Notifications
   * const Notifications = await prisma.notifications.create({
   *   data: {
   *     // ... data to create a Notifications
   *   }
   * })
   * 
   */
  create<T extends NotificationsCreateArgs>(args: Prisma.SelectSubset<T, NotificationsCreateArgs<ExtArgs>>): Prisma.Prisma__NotificationsClient<runtime.Types.Result.GetResult<Prisma.$NotificationsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Notifications.
   * @param {NotificationsCreateManyArgs} args - Arguments to create many Notifications.
   * @example
   * // Create many Notifications
   * const notifications = await prisma.notifications.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NotificationsCreateManyArgs>(args?: Prisma.SelectSubset<T, NotificationsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Notifications.
   * @param {NotificationsDeleteArgs} args - Arguments to delete one Notifications.
   * @example
   * // Delete one Notifications
   * const Notifications = await prisma.notifications.delete({
   *   where: {
   *     // ... filter to delete one Notifications
   *   }
   * })
   * 
   */
  delete<T extends NotificationsDeleteArgs>(args: Prisma.SelectSubset<T, NotificationsDeleteArgs<ExtArgs>>): Prisma.Prisma__NotificationsClient<runtime.Types.Result.GetResult<Prisma.$NotificationsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Notifications.
   * @param {NotificationsUpdateArgs} args - Arguments to update one Notifications.
   * @example
   * // Update one Notifications
   * const notifications = await prisma.notifications.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NotificationsUpdateArgs>(args: Prisma.SelectSubset<T, NotificationsUpdateArgs<ExtArgs>>): Prisma.Prisma__NotificationsClient<runtime.Types.Result.GetResult<Prisma.$NotificationsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Notifications.
   * @param {NotificationsDeleteManyArgs} args - Arguments to filter Notifications to delete.
   * @example
   * // Delete a few Notifications
   * const { count } = await prisma.notifications.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NotificationsDeleteManyArgs>(args?: Prisma.SelectSubset<T, NotificationsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Notifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Notifications
   * const notifications = await prisma.notifications.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NotificationsUpdateManyArgs>(args: Prisma.SelectSubset<T, NotificationsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Notifications.
   * @param {NotificationsUpsertArgs} args - Arguments to update or create a Notifications.
   * @example
   * // Update or create a Notifications
   * const notifications = await prisma.notifications.upsert({
   *   create: {
   *     // ... data to create a Notifications
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Notifications we want to update
   *   }
   * })
   */
  upsert<T extends NotificationsUpsertArgs>(args: Prisma.SelectSubset<T, NotificationsUpsertArgs<ExtArgs>>): Prisma.Prisma__NotificationsClient<runtime.Types.Result.GetResult<Prisma.$NotificationsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Notifications that matches the filter.
   * @param {NotificationsFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const notifications = await prisma.notifications.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.NotificationsFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a Notifications.
   * @param {NotificationsAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const notifications = await prisma.notifications.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.NotificationsAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of Notifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationsCountArgs} args - Arguments to filter Notifications to count.
   * @example
   * // Count the number of Notifications
   * const count = await prisma.notifications.count({
   *   where: {
   *     // ... the filter for the Notifications we want to count
   *   }
   * })
  **/
  count<T extends NotificationsCountArgs>(
    args?: Prisma.Subset<T, NotificationsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NotificationsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Notifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NotificationsAggregateArgs>(args: Prisma.Subset<T, NotificationsAggregateArgs>): Prisma.PrismaPromise<GetNotificationsAggregateType<T>>

  /**
   * Group by Notifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NotificationsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NotificationsGroupByArgs['orderBy'] }
      : { orderBy?: NotificationsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NotificationsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNotificationsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Notifications model
 */
readonly fields: NotificationsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Notifications.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NotificationsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.Notifications$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Notifications$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Notifications model
 */
export interface NotificationsFieldRefs {
  readonly id: Prisma.FieldRef<"Notifications", 'String'>
  readonly body: Prisma.FieldRef<"Notifications", 'String'>
  readonly createdAt: Prisma.FieldRef<"Notifications", 'DateTime'>
  readonly userId: Prisma.FieldRef<"Notifications", 'String'>
}
    

// Custom InputTypes
/**
 * Notifications findUnique
 */
export type NotificationsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notifications
   */
  select?: Prisma.NotificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notifications
   */
  omit?: Prisma.NotificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationsInclude<ExtArgs> | null
  /**
   * Filter, which Notifications to fetch.
   */
  where: Prisma.NotificationsWhereUniqueInput
}

/**
 * Notifications findUniqueOrThrow
 */
export type NotificationsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notifications
   */
  select?: Prisma.NotificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notifications
   */
  omit?: Prisma.NotificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationsInclude<ExtArgs> | null
  /**
   * Filter, which Notifications to fetch.
   */
  where: Prisma.NotificationsWhereUniqueInput
}

/**
 * Notifications findFirst
 */
export type NotificationsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notifications
   */
  select?: Prisma.NotificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notifications
   */
  omit?: Prisma.NotificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationsInclude<ExtArgs> | null
  /**
   * Filter, which Notifications to fetch.
   */
  where?: Prisma.NotificationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notifications to fetch.
   */
  orderBy?: Prisma.NotificationsOrderByWithRelationInput | Prisma.NotificationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Notifications.
   */
  cursor?: Prisma.NotificationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Notifications.
   */
  distinct?: Prisma.NotificationsScalarFieldEnum | Prisma.NotificationsScalarFieldEnum[]
}

/**
 * Notifications findFirstOrThrow
 */
export type NotificationsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notifications
   */
  select?: Prisma.NotificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notifications
   */
  omit?: Prisma.NotificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationsInclude<ExtArgs> | null
  /**
   * Filter, which Notifications to fetch.
   */
  where?: Prisma.NotificationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notifications to fetch.
   */
  orderBy?: Prisma.NotificationsOrderByWithRelationInput | Prisma.NotificationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Notifications.
   */
  cursor?: Prisma.NotificationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Notifications.
   */
  distinct?: Prisma.NotificationsScalarFieldEnum | Prisma.NotificationsScalarFieldEnum[]
}

/**
 * Notifications findMany
 */
export type NotificationsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notifications
   */
  select?: Prisma.NotificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notifications
   */
  omit?: Prisma.NotificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationsInclude<ExtArgs> | null
  /**
   * Filter, which Notifications to fetch.
   */
  where?: Prisma.NotificationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notifications to fetch.
   */
  orderBy?: Prisma.NotificationsOrderByWithRelationInput | Prisma.NotificationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Notifications.
   */
  cursor?: Prisma.NotificationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notifications.
   */
  skip?: number
  distinct?: Prisma.NotificationsScalarFieldEnum | Prisma.NotificationsScalarFieldEnum[]
}

/**
 * Notifications create
 */
export type NotificationsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notifications
   */
  select?: Prisma.NotificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notifications
   */
  omit?: Prisma.NotificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationsInclude<ExtArgs> | null
  /**
   * The data needed to create a Notifications.
   */
  data: Prisma.XOR<Prisma.NotificationsCreateInput, Prisma.NotificationsUncheckedCreateInput>
}

/**
 * Notifications createMany
 */
export type NotificationsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Notifications.
   */
  data: Prisma.NotificationsCreateManyInput | Prisma.NotificationsCreateManyInput[]
}

/**
 * Notifications update
 */
export type NotificationsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notifications
   */
  select?: Prisma.NotificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notifications
   */
  omit?: Prisma.NotificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationsInclude<ExtArgs> | null
  /**
   * The data needed to update a Notifications.
   */
  data: Prisma.XOR<Prisma.NotificationsUpdateInput, Prisma.NotificationsUncheckedUpdateInput>
  /**
   * Choose, which Notifications to update.
   */
  where: Prisma.NotificationsWhereUniqueInput
}

/**
 * Notifications updateMany
 */
export type NotificationsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Notifications.
   */
  data: Prisma.XOR<Prisma.NotificationsUpdateManyMutationInput, Prisma.NotificationsUncheckedUpdateManyInput>
  /**
   * Filter which Notifications to update
   */
  where?: Prisma.NotificationsWhereInput
  /**
   * Limit how many Notifications to update.
   */
  limit?: number
}

/**
 * Notifications upsert
 */
export type NotificationsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notifications
   */
  select?: Prisma.NotificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notifications
   */
  omit?: Prisma.NotificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationsInclude<ExtArgs> | null
  /**
   * The filter to search for the Notifications to update in case it exists.
   */
  where: Prisma.NotificationsWhereUniqueInput
  /**
   * In case the Notifications found by the `where` argument doesn't exist, create a new Notifications with this data.
   */
  create: Prisma.XOR<Prisma.NotificationsCreateInput, Prisma.NotificationsUncheckedCreateInput>
  /**
   * In case the Notifications was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NotificationsUpdateInput, Prisma.NotificationsUncheckedUpdateInput>
}

/**
 * Notifications delete
 */
export type NotificationsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notifications
   */
  select?: Prisma.NotificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notifications
   */
  omit?: Prisma.NotificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationsInclude<ExtArgs> | null
  /**
   * Filter which Notifications to delete.
   */
  where: Prisma.NotificationsWhereUniqueInput
}

/**
 * Notifications deleteMany
 */
export type NotificationsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Notifications to delete
   */
  where?: Prisma.NotificationsWhereInput
  /**
   * Limit how many Notifications to delete.
   */
  limit?: number
}

/**
 * Notifications findRaw
 */
export type NotificationsFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * Notifications aggregateRaw
 */
export type NotificationsAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * Notifications.user
 */
export type Notifications$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Notifications without action
 */
export type NotificationsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notifications
   */
  select?: Prisma.NotificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notifications
   */
  omit?: Prisma.NotificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationsInclude<ExtArgs> | null
}
