import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import SideBar from "@/components/SideBar";
import FollowBar from "@/components/FollowBar";
import { Toaster } from "react-hot-toast";
import ModalProvider from "@/components/ModalProvider";

const font = Barlow({
  subsets: ["latin"],
  weight: ["500", "400", "200", "100"]
})

export const metadata: Metadata = {
  title: "Twitter",
  description: "Generated by create next app",
  icons :"/logo.png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={` ${font.className} antialiased`}
        >
          <main className="h-screen">
            <Toaster />
            <ModalProvider/>
            <div className="container h-full flex mx-auto  max-w-6xl">
              <div className="flex-1"><SideBar /></div>
              <div className="flex-2 border-x border-neutral-800 ">{children}</div>
              <div className="flex-1"><FollowBar /></div>
            </div>
          </main>
        </body>
      </Provider>
    </html >
  );
}

// 1280